# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_install_hook_types: 
  - pre-commit
  - post-checkout

repos:

  # Basic checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-toml
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer

  # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
    - id: ruff-check   # linter
    - id: ruff-format  # formatter

  # reorder-python-imports
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.16.0
    hooks:
    - id: reorder-python-imports

  # Clean up cached python files (__pycache__, *.py[co]) after switching branches
  - repo: https://github.com/mferber/pre-commit-pycache-cleanup
    rev: v0.0.1
    hooks:
    - id: clean-pycache

  # Mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
    - id: mypy
      additional_dependencies:
      - tokenize-rt
      - types-requests
      - types-PyYAML
