# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  # Basic checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer

  # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff-check   # linter
      - id: ruff-format  # formatter

  # Mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
    - id: mypy
      additional_dependencies:
      - types-requests
      - types-PyYAML

  # Clean up cached python files (__pycache__, *.py[co]) after switching branches
  - repo: https://github.com/mferber/pre-commit-pycache-cleanup
    rev: v0.0.3
    hooks:
    - id: clean-pycache
