[project]
name = "tvchartapi"
version = "0.0.1"
description = "Backend API for TV chart tracker"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "litestar[standard]>=2.18.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.3",
]
